import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/resources/sass/main.scss"
import { getLocale, getMessages } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"

import { cn } from "@/lib/utils"

const font = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  const locale = await getLocale()

  const messages = await getMessages()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={ cn("min-h-screen bg-background font-sans antialiased", font.variable) }>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
